import type { SettingsNamespace, SettingObject } from './schema.ts'

// DSH 0.2.0-rc.2 settings.describe(), captured by e2e-dsh/rpc.spec.ts.
// Reference ids are local; only validation metadata is copied. apiKey uses the
// renderer's password role. No submitted key value is stored in these fixtures.
const published: { ns: string; autoGenerate: boolean; schema: unknown; base: SettingObject }[] = [
  { ns: "agent-default-model", autoGenerate: false, base: {"provider":"deepseek-official","model":"deepseek-flash"}, schema: { uid: 0, refs: {
    0: {"type":"object","dict":{"provider":1,"model":2,"reasoningEffort":3}},
    1: {"type":"string","meta":{"required":true}},
    2: {"type":"string","meta":{"required":true}},
    3: {"type":"string"},
  } } },
  { ns: "subagent-model-selection-settings", autoGenerate: true, base: {"enabled":false,"allowedModels":[]}, schema: { uid: 0, refs: {
    0: {"type":"object","dict":{"enabled":1,"allowedModels":2}},
    1: {"type":"boolean"},
    2: {"type":"array","inner":3},
    3: {"type":"object","dict":{"provider":4,"model":5}},
    4: {"type":"string","meta":{"min":1,"required":true}},
    5: {"type":"string","meta":{"min":1,"required":true}},
  } } },
  { ns: "permission", autoGenerate: false, base: {}, schema: { uid: 0, refs: {
    0: {"type":"object","dict":{"defaultPreset":1}},
    1: {"type":"string"},
  } } },
  { ns: "agent-preset-registry", autoGenerate: false, base: {}, schema: { uid: 0, refs: {
    0: {"type":"object","dict":{"selectedDefault":1}},
    1: {"type":"string"},
  } } },
  { ns: "agent-loop", autoGenerate: true, base: {"maxParallelToolCalls":10}, schema: { uid: 0, refs: {
    0: {"type":"object","dict":{"maxParallelToolCalls":1}},
    1: {"type":"number","meta":{"step":1,"min":1}},
  } } },
  { ns: "llm-deepseek", autoGenerate: false, base: {"maxTokens":256000,"defaultContextWindow":1000000,"models":[{"id":"deepseek-flash","name":"DeepSeek-V41-Flash","contextWindow":1000000,"inputModalities":["text","image"],"systemPromptUpdate":"in-history","toolUpdate":"addition-only"},{"id":"deepseek-v4-pro","name":"DeepSeek-V4-Pro","description":"Stronger agentic coding, knowledge, and difficult reasoning; suited to complex or quality-critical tasks at higher cost.","contextWindow":1000000,"inputModalities":["text"]}],"streamIdleTimeoutMs":300000,"maxRequestFilesBytes":134217728,"maxInlineRequestImageBytes":20971520,"maxImagesPerRequest":600,"imageOffloadByteQuantum":67108864,"inlineImageOffloadByteQuantum":10485760,"imageOffloadCountQuantum":20,"filesApiTimeoutMs":60000,"fileExpiresAfterSeconds":604800,"fileRefreshMarginSeconds":3600,"fileQuotaCleanupBatch":100,"apiKeyEnv":"DEEPSEEK_API_KEY"}, schema: { uid: 0, refs: {
    0: {"type":"object","dict":{"baseURL":1,"thinking":2,"reasoningEffort":5,"maxTokens":10,"defaultContextWindow":11,"models":12,"streamIdleTimeoutMs":31,"maxRequestFilesBytes":32,"maxInlineRequestImageBytes":33,"maxImagesPerRequest":34,"imageOffloadByteQuantum":35,"inlineImageOffloadByteQuantum":36,"imageOffloadCountQuantum":37,"filesApiTimeoutMs":38,"fileExpiresAfterSeconds":39,"fileRefreshMarginSeconds":40,"fileQuotaCleanupBatch":41,"retryPolicy":42,"apiKeyEnv":54}},
    1: {"type":"string"},
    2: {"type":"union","list":[3,4]},
    3: {"type":"const","value":"enabled","meta":{"required":true}},
    4: {"type":"const","value":"disabled","meta":{"required":true}},
    5: {"type":"union","list":[6,7,8,9]},
    6: {"type":"const","value":"off","meta":{"required":true}},
    7: {"type":"const","value":"low","meta":{"required":true}},
    8: {"type":"const","value":"high","meta":{"required":true}},
    9: {"type":"const","value":"max","meta":{"required":true}},
    10: {"type":"number","meta":{"step":1,"min":1,"max":9007199254740991}},
    11: {"type":"number","meta":{"step":1,"min":1}},
    12: {"type":"array","inner":13},
    13: {"type":"object","dict":{"id":14,"name":15,"description":16,"contextWindow":17,"maxTokens":18,"inputModalities":19,"imagePixelBudget":23,"imageMaxBytes":26,"systemPromptUpdate":27,"toolUpdate":28}},
    14: {"type":"string","meta":{"required":true}},
    15: {"type":"string"},
    16: {"type":"string"},
    17: {"type":"number","meta":{"step":1,"min":1}},
    18: {"type":"number","meta":{"step":1,"min":1}},
    19: {"type":"array","meta":{"min":1},"inner":20},
    20: {"type":"union","list":[21,22]},
    21: {"type":"const","value":"text","meta":{"required":true}},
    22: {"type":"const","value":"image","meta":{"required":true}},
    23: {"type":"union","list":[24,25]},
    24: {"type":"number","meta":{"step":1,"min":1}},
    25: {"type":"const","value":"low","meta":{"required":true}},
    26: {"type":"number","meta":{"step":1,"min":1}},
    27: {"type":"const","value":"in-history"},
    28: {"type":"union","list":[29,30]},
    29: {"type":"const","value":"in-history","meta":{"required":true}},
    30: {"type":"const","value":"addition-only","meta":{"required":true}},
    31: {"type":"number","meta":{"min":5e-324,"max":2147483647}},
    32: {"type":"number","meta":{"step":1,"min":1}},
    33: {"type":"number","meta":{"step":1,"min":1}},
    34: {"type":"number","meta":{"step":1,"min":1}},
    35: {"type":"number","meta":{"step":1,"min":1}},
    36: {"type":"number","meta":{"step":1,"min":1}},
    37: {"type":"number","meta":{"step":1,"min":1}},
    38: {"type":"number","meta":{"min":5e-324,"max":2147483647}},
    39: {"type":"number","meta":{"step":1,"min":3600,"max":2592000}},
    40: {"type":"number","meta":{"step":1,"min":0}},
    41: {"type":"number","meta":{"step":1,"min":1,"max":1000}},
    42: {"type":"union","list":[43,52]},
    43: {"type":"object","dict":{"mode":44,"maxRetries":45,"retryableCodes":46,"backoff":48}},
    44: {"type":"const","value":"normal","meta":{"required":true}},
    45: {"type":"number","meta":{"step":1,"min":0,"max":9007199254740991}},
    46: {"type":"array","inner":47},
    47: {"type":"string"},
    48: {"type":"object","dict":{"initialDelayMs":49,"maxDelayMs":50,"jitterRatio":51}},
    49: {"type":"number","meta":{"max":2147483647}},
    50: {"type":"number","meta":{"max":2147483647}},
    51: {"type":"number","meta":{"min":0,"max":1}},
    52: {"type":"object","dict":{"mode":53,"backoff":48}},
    53: {"type":"const","value":"always","meta":{"required":true}},
    54: {"type":"string"},
  } } },
  { ns: "llm-pi-ai", autoGenerate: false, base: {"providers":{}}, schema: { uid: 0, refs: {
    0: {"type":"object","dict":{"providers":1}},
    1: {"type":"dict","inner":2,"sKey":143},
    2: {"type":"object","dict":{"apiKeyEnv":3,"displayName":4,"api":5,"baseURL":9,"models":10,"modelOverrides":91,"compat":34,"defaultContextWindow":94,"defaultMaxTokens":95,"defaultInput":96,"headers":100,"reasoning":103,"thinkingBudgets":111,"cacheRetention":116,"transport":120,"timeoutMs":125,"websocketConnectTimeoutMs":126,"streamIdleTimeoutMs":127,"maxRequestImageBytes":128,"requestImagePixelBudget":129,"requestImageMaxBytes":130,"retryPolicy":131}},
    3: {"type":"string"},
    4: {"type":"string"},
    5: {"type":"union","list":[6,7,8]},
    6: {"type":"const","value":"openai-completions","meta":{"required":true}},
    7: {"type":"const","value":"openai-responses","meta":{"required":true}},
    8: {"type":"const","value":"anthropic-messages","meta":{"required":true}},
    9: {"type":"string"},
    10: {"type":"array","inner":11},
    11: {"type":"object","dict":{"id":12,"name":13,"contextWindow":14,"maxTokens":15,"input":16,"reasoningEfforts":20,"compat":34}},
    12: {"type":"string","meta":{"required":true}},
    13: {"type":"string"},
    14: {"type":"number","meta":{"step":1,"min":1}},
    15: {"type":"number","meta":{"step":1,"min":1}},
    16: {"type":"array","inner":17},
    17: {"type":"union","list":[18,19]},
    18: {"type":"const","value":"text","meta":{"required":true}},
    19: {"type":"const","value":"image","meta":{"required":true}},
    20: {"type":"union","list":[21,22]},
    21: {"type":"const","value":false},
    22: {"type":"dict","inner":23,"sKey":26},
    23: {"type":"union","list":[24,25]},
    24: {"type":"string"},
    25: {"type":"const","value":null},
    26: {"type":"union","list":[27,28,29,30,31,32,33]},
    27: {"type":"const","value":"off","meta":{"required":true}},
    28: {"type":"const","value":"minimal","meta":{"required":true}},
    29: {"type":"const","value":"low","meta":{"required":true}},
    30: {"type":"const","value":"medium","meta":{"required":true}},
    31: {"type":"const","value":"high","meta":{"required":true}},
    32: {"type":"const","value":"xhigh","meta":{"required":true}},
    33: {"type":"const","value":"max","meta":{"required":true}},
    34: {"type":"object","dict":{"supportsStore":35,"supportsDeveloperRole":36,"supportsReasoningEffort":37,"supportsUsageInStreaming":38,"supportsFinishReason":39,"maxTokensField":40,"requiresToolResultName":43,"requiresAssistantAfterToolResult":44,"requiresThinkingAsText":45,"requiresReasoningContentOnAssistantMessages":46,"thinkingFormat":47,"chatTemplateKwargs":59,"chatTemplateArgs":72,"supportsThinkingTokenBudget":74,"thinkingTokenBudgetField":75,"vllmPriority":79,"supportsMaxOutputTokens":80,"supportsStrictMode":81,"cacheControlFormat":82,"supportsLongCacheRetention":84,"supportsEagerToolInputStreaming":85,"supportsCacheControlOnTools":86,"supportsTemperature":87,"forceAdaptiveThinking":88,"allowEmptySignature":89,"supportsStrictTools":90}},
    35: {"type":"boolean"},
    36: {"type":"boolean"},
    37: {"type":"boolean"},
    38: {"type":"boolean"},
    39: {"type":"boolean"},
    40: {"type":"union","list":[41,42]},
    41: {"type":"const","value":"max_completion_tokens","meta":{"required":true}},
    42: {"type":"const","value":"max_tokens","meta":{"required":true}},
    43: {"type":"boolean"},
    44: {"type":"boolean"},
    45: {"type":"boolean"},
    46: {"type":"boolean"},
    47: {"type":"union","list":[48,49,50,51,52,53,54,55,56,57,58]},
    48: {"type":"const","value":"openai","meta":{"required":true}},
    49: {"type":"const","value":"deepseek","meta":{"required":true}},
    50: {"type":"const","value":"openrouter","meta":{"required":true}},
    51: {"type":"const","value":"together","meta":{"required":true}},
    52: {"type":"const","value":"baseten","meta":{"required":true}},
    53: {"type":"const","value":"zai","meta":{"required":true}},
    54: {"type":"const","value":"qwen","meta":{"required":true}},
    55: {"type":"const","value":"chat-template","meta":{"required":true}},
    56: {"type":"const","value":"qwen-chat-template","meta":{"required":true}},
    57: {"type":"const","value":"string-thinking","meta":{"required":true}},
    58: {"type":"const","value":"ant-ling","meta":{"required":true}},
    59: {"type":"dict","inner":60,"sKey":71},
    60: {"type":"union","list":[61,62,63,64,65]},
    61: {"type":"string"},
    62: {"type":"number"},
    63: {"type":"boolean"},
    64: {"type":"const","value":null},
    65: {"type":"object","dict":{"$var":66,"omitWhenOff":70}},
    66: {"type":"union","meta":{"required":true},"list":[67,68,69]},
    67: {"type":"const","value":"thinking.enabled","meta":{"required":true}},
    68: {"type":"const","value":"thinking.effort","meta":{"required":true}},
    69: {"type":"const","value":"thinking.budget","meta":{"required":true}},
    70: {"type":"boolean"},
    71: {"type":"string"},
    72: {"type":"dict","inner":60,"sKey":73},
    73: {"type":"string"},
    74: {"type":"boolean"},
    75: {"type":"union","list":[76,77,78]},
    76: {"type":"const","value":"thinking_token_budget","meta":{"required":true}},
    77: {"type":"const","value":"thinking_budget","meta":{"required":true}},
    78: {"type":"const","value":"thinking_budget_tokens","meta":{"required":true}},
    79: {"type":"number","meta":{"step":1}},
    80: {"type":"boolean"},
    81: {"type":"boolean"},
    82: {"type":"union","list":[83]},
    83: {"type":"const","value":"anthropic","meta":{"required":true}},
    84: {"type":"boolean"},
    85: {"type":"boolean"},
    86: {"type":"boolean"},
    87: {"type":"boolean"},
    88: {"type":"boolean"},
    89: {"type":"boolean"},
    90: {"type":"boolean"},
    91: {"type":"dict","inner":92,"sKey":93},
    92: {"type":"object","dict":{"name":13,"contextWindow":14,"maxTokens":15,"input":16,"reasoningEfforts":20,"compat":34}},
    93: {"type":"string"},
    94: {"type":"number","meta":{"step":1,"min":1}},
    95: {"type":"number","meta":{"step":1,"min":1}},
    96: {"type":"array","inner":97},
    97: {"type":"union","list":[98,99]},
    98: {"type":"const","value":"text","meta":{"required":true}},
    99: {"type":"const","value":"image","meta":{"required":true}},
    100: {"type":"dict","inner":101,"sKey":102},
    101: {"type":"string"},
    102: {"type":"string"},
    103: {"type":"union","list":[104,105,106,107,108,109,110]},
    104: {"type":"const","value":"off","meta":{"required":true}},
    105: {"type":"const","value":"minimal","meta":{"required":true}},
    106: {"type":"const","value":"low","meta":{"required":true}},
    107: {"type":"const","value":"medium","meta":{"required":true}},
    108: {"type":"const","value":"high","meta":{"required":true}},
    109: {"type":"const","value":"xhigh","meta":{"required":true}},
    110: {"type":"const","value":"max","meta":{"required":true}},
    111: {"type":"object","dict":{"minimal":112,"low":113,"medium":114,"high":115}},
    112: {"type":"number"},
    113: {"type":"number"},
    114: {"type":"number"},
    115: {"type":"number"},
    116: {"type":"union","list":[117,118,119]},
    117: {"type":"const","value":"none","meta":{"required":true}},
    118: {"type":"const","value":"short","meta":{"required":true}},
    119: {"type":"const","value":"long","meta":{"required":true}},
    120: {"type":"union","list":[121,122,123,124]},
    121: {"type":"const","value":"sse","meta":{"required":true}},
    122: {"type":"const","value":"websocket","meta":{"required":true}},
    123: {"type":"const","value":"websocket-cached","meta":{"required":true}},
    124: {"type":"const","value":"auto","meta":{"required":true}},
    125: {"type":"number","meta":{"step":1,"min":0}},
    126: {"type":"number","meta":{"step":1,"min":0}},
    127: {"type":"number","meta":{"min":5e-324,"max":2147483647}},
    128: {"type":"number","meta":{"step":1,"min":1}},
    129: {"type":"number","meta":{"step":1,"min":1}},
    130: {"type":"number","meta":{"step":1,"min":1}},
    131: {"type":"union","list":[132,141]},
    132: {"type":"object","dict":{"mode":133,"maxRetries":134,"retryableCodes":135,"backoff":137}},
    133: {"type":"const","value":"normal","meta":{"required":true}},
    134: {"type":"number","meta":{"step":1,"min":0,"max":9007199254740991}},
    135: {"type":"array","inner":136},
    136: {"type":"string"},
    137: {"type":"object","dict":{"initialDelayMs":138,"maxDelayMs":139,"jitterRatio":140}},
    138: {"type":"number","meta":{"max":2147483647}},
    139: {"type":"number","meta":{"max":2147483647}},
    140: {"type":"number","meta":{"min":0,"max":1}},
    141: {"type":"object","dict":{"mode":142,"backoff":137}},
    142: {"type":"const","value":"always","meta":{"required":true}},
    143: {"type":"string"},
  } } },
  { ns: "web-search-deepseek", autoGenerate: true, base: {"apiKeyEnv":"DEEPSEEK_API_KEY","model":"deepseek-v4-flash","apiVersion":"2023-06-01","maxTokens":4096,"maxUses":5}, schema: { uid: 0, refs: {
    0: {"type":"object","dict":{"apiKey":1,"apiKeyEnv":2,"baseURL":3,"model":4,"apiVersion":5,"maxTokens":6,"maxUses":7}},
    1: {"type":"string","meta":{"role":"password"}},
    2: {"type":"string"},
    3: {"type":"string"},
    4: {"type":"string"},
    5: {"type":"string"},
    6: {"type":"number","meta":{"step":1,"min":1}},
    7: {"type":"number","meta":{"step":1,"min":1}},
  } } },
  { ns: "bash-sandbox", autoGenerate: true, base: {"timeoutMs":60000,"maxTimeoutMs":600000,"maxOutputBytes":64000,"maxSpillBytes":67108864,"graceMs":3000}, schema: { uid: 0, refs: {
    0: {"type":"object","dict":{"cwd":1,"timeoutMs":2,"maxTimeoutMs":3,"maxOutputBytes":4,"maxSpillBytes":5,"graceMs":6}},
    1: {"type":"string"},
    2: {"type":"number"},
    3: {"type":"number"},
    4: {"type":"number"},
    5: {"type":"number"},
    6: {"type":"number"},
  } } },
  { ns: "locale", autoGenerate: false, base: {}, schema: { uid: 0, refs: {
    0: {"type":"object","dict":{"preference":1}},
    1: {"type":"string","meta":{"pattern":{"source":"^[A-Za-z]{2,8}(?:-[A-Za-z0-9]{1,8})*$","flags":"u"},"required":false}},
  } } },
  { ns: "ui-theme", autoGenerate: false, base: {"preference":"system","fontSize":14}, schema: { uid: 0, refs: {
    0: {"type":"object","dict":{"preference":1,"fontSize":5}},
    1: {"type":"union","list":[2,3,4]},
    2: {"type":"const","value":"light","meta":{"required":true}},
    3: {"type":"const","value":"dark","meta":{"required":true}},
    4: {"type":"const","value":"system","meta":{"required":true}},
    5: {"type":"number","meta":{"step":1,"min":10,"max":22}},
  } } },
]

/** Detached public settings for the scripted model/provider configuration. */
export function settingsFixtures(): SettingsNamespace[] {
  const rows: SettingsNamespace[] = published.map(row => {
    const base = structuredClone(row.base)
    // The mock LLM advertises these routes; this is configuration, not a schema extension.
    if (row.ns === 'agent-default-model') Object.assign(base, { provider: 'deepseek', model: 'deepseek-v4' })
    if (row.ns === 'llm-pi-ai') base.providers = { cloud: { apiKeyEnv: 'PI_AI_API_KEY' } }
    const user: SettingObject = row.ns === 'agent-default-model' ? { reasoningEffort: 'high' } : {}
    return { ...row, schema: structuredClone(row.schema), base, user, value: { ...structuredClone(base), ...user }, revision: 0, applies: 'live' }
  })
  rows.push(exampleFixture())
  return rows
}

/** All invented form types live under this explicitly fictional namespace. */
function exampleFixture(): SettingsNamespace {
  const base: SettingObject = { enabled: true, name: '追加機能', timeout: 30, mode: '標準', retry: { enabled: true, interval: 2 }, models: ['基本モデル', '補助モデル'], labels: { primary: '既定' }, custom: null, localProvider: {} }
  const user: SettingObject = { timeout: 45, retry: { interval: 3 } }
  return { ns: 'example-extension', autoGenerate: true, revision: 0, applies: 'live', base, user,
    value: { ...structuredClone(base), timeout: 45, retry: { enabled: true, interval: 3 } },
    schema: { uid: 0, refs: {
      0: { type: 'object', dict: { enabled: 1, name: 2, timeout: 3, mode: 4, retry: 8, models: 11, labels: 13, custom: 14, protectedInput: 15, localProvider: 16 } },
      1: { type: 'boolean', meta: { title: '有効にする' } },
      2: { type: 'string', meta: { title: '名前', required: true, min: 1 } },
      3: { type: 'number', meta: { title: '待機時間', min: 1, max: 120, step: 1 } },
      4: { type: 'union', list: [5, 6, 7], meta: { title: '動作モード' } },
      5: { type: 'const', value: '標準' }, 6: { type: 'const', value: '慎重' }, 7: { type: 'const', value: '高速' },
      8: { type: 'object', dict: { enabled: 9, interval: 10 }, meta: { title: '再試行' } },
      9: { type: 'boolean', meta: { title: '再試行する' } },
      10: { type: 'number', meta: { title: '間隔', min: 1, max: 10, step: 1 } },
      11: { type: 'array', inner: 12, meta: { title: 'モデルの候補' } }, 12: { type: 'string' },
      13: { type: 'dict', inner: 12, meta: { title: 'ラベル' } },
      14: { type: 'custom', meta: { title: '拡張項目' } },
      15: { type: 'string', meta: { title: '保護された項目', role: 'password' } },
      16: { type: 'object', dict: {}, meta: { title: 'ローカル提供元' } },
    } },
  }
}
