import { test, expect, visit, shot, button } from './helpers'

for (const width of [390, 375]) {
  test(`02h ${width}pxで注入文脈の原文・参照元・添付を開き、自分の発言と区別できる`, async ({ page }) => {
    await page.setViewportSize({ width, height: 844 })
    await visit(page, '/s/chat-injected-context', 'chat-injected-context')
    await expect(page.getByLabel('自分のメッセージ', { exact: true })).toHaveCount(1)
    await expect(page.getByLabel('自分のメッセージ', { exact: true })).toHaveText('私が送った検証用メッセージ')
    const system = page.locator('details').filter({ has: page.locator('summary').filter({ hasText: 'システムプロンプト' }) })
    const injected = page.locator('details').filter({ has: page.locator('summary').filter({ hasText: '追加された文脈' }) })
    const recalled = page.locator('details').filter({ has: page.locator('summary').filter({ hasText: '別の会話から参照' }) })
    const file = injected.locator('.chat-file').filter({ hasText: '文脈の資料.txt' })
    await expect(system.locator('pre')).toBeHidden()
    await expect(injected.locator('pre')).toBeHidden()
    await expect(file).toHaveCount(1)
    await expect(file).toBeHidden()
    await expect(recalled.locator('pre')).toBeHidden()
    await expect(injected.locator('summary')).toContainText('検証用プラグイン')
    await expect(recalled.locator('summary')).toContainText('検証用の参照会話')
    await shot(page, `02-context-${width}-collapsed`)

    await system.locator('summary').click()
    await expect(system.locator('pre')).toHaveText('システムの検証用原文\n<b>そのまま読む</b>')
    await expect(system.locator('b')).toHaveCount(0)
    await system.locator('summary').click()
    await injected.locator('summary').click()
    await expect(injected.locator('pre')).toHaveText('<system-reminder>\n# 追加された検証用原文\n<b>そのまま読む</b>\n</system-reminder>')
    await expect(injected.locator('b, system-reminder')).toHaveCount(0)
    await expect(file).toBeVisible()
    await expect(file).toContainText('文脈の資料.txt')
    await expect(injected.getByText('2.0 KB', { exact: true })).toBeVisible()
    const expand = injected.getByRole('button', { name: '文脈の画像.pngを全画面で表示', exact: true })
    await expect(expand.locator('img')).toHaveJSProperty('naturalWidth', 1)
    await shot(page, `02-context-${width}-expanded`)
    await expand.click()
    const viewer = page.getByRole('dialog', { name: '画像の表示' })
    await expect(viewer).toBeVisible()
    await expect(viewer.getByRole('img', { name: '文脈の画像.png', exact: true })).toHaveJSProperty('naturalWidth', 1)
    await shot(page, `02-context-${width}-image`)
    await button(page, '閉じる').click()
    await expect(viewer).toHaveCount(0)
    await injected.locator('summary').click()
    await expect(injected.locator('pre')).toBeHidden()
    await expect(expand).toBeHidden()
    await recalled.locator('summary').click()
    await expect(recalled.locator('pre')).toHaveText('別の会話の検証用原文')
    await shot(page, `02-context-${width}-recall`)
  })
}
