import { test, expect, visit, shot, button } from './helpers'

test('09 continuableの子に追記し、one-shotの子は読むだけにする', async ({ page }) => {
  await visit(page, '/s/session-tools-review')
  const input = page.getByLabel('メッセージ入力欄', { exact: true })
  await expect(page.getByRole('heading', { name: '承認シートの見直し', exact: true })).toBeVisible()
  await shot(page, '09-continuable-before-send')
  await expect(input).toBeVisible()
  await input.fill('子の会話への追加依頼を確認してください')
  await button(page, '順番待ち').click()
  await expect(input).toHaveValue('')
  await expect(button(page, '順番待ち 1 件')).toBeVisible()
  await shot(page, '09-continuable-queued')
  await page.getByRole('tab', { name: 'トレース', exact: true }).click()
  await expect(input).toHaveCount(0)
  await page.getByRole('tab', { name: 'チャット', exact: true }).click()
  await expect(button(page, '順番待ち 1 件')).toBeVisible()
  await visit(page, '/s/session-tools-tests')
  await expect(page.getByLabel('メッセージ入力欄', { exact: true })).toHaveCount(0)
  await expect(page.getByText('このサブエージェントの会話は読むだけです。', { exact: true })).toBeVisible()
  await shot(page, '09-one-shot-readonly')
})

test('09 continuableの子でも切断中の下書きを保ち、再接続後に一度だけ送る', async ({ page }) => {
  await page.setViewportSize({ width: 375, height: 812 })
  await visit(page, '/s/session-tools-review', 'disconnected')
  const input = page.getByLabel('メッセージ入力欄', { exact: true })
  const text = '再接続後に子の会話へ追加する依頼'
  await input.fill(text)
  await expect(button(page, '順番待ち')).toBeDisabled()
  await shot(page, '09-child-disconnected-draft')
  await button(page, '再接続').click()
  await expect(button(page, '順番待ち')).toBeEnabled()
  await expect(input).toHaveValue(text)
  await button(page, '順番待ち').click()
  await expect(input).toHaveValue('')
  await button(page, '順番待ち 1 件').click()
  await expect(page.getByText(text, { exact: true })).toHaveCount(1)
  await shot(page, '09-child-reconnected-queue')
})

test('09 continuableの子の実行へ割り込み、停止後も追記できる', async ({ page }) => {
  await visit(page, '/s/session-tools-review')
  const input = page.getByLabel('メッセージ入力欄', { exact: true })
  const text = '子の実行への割り込みを確認する'
  await input.fill(text)
  await button(page, '送り方を選ぶ').click()
  await button(page, '割り込み').click()
  await expect(input).toHaveValue('')
  await button(page, '実行を停止').click()
  await expect(button(page, '送信')).toBeVisible()
  await expect(page.getByLabel('自分のメッセージ', { exact: true }).filter({ hasText: text })).toHaveCount(1)
  await expect(page).toHaveURL(/#\/s\/session-tools-review$/)
  await input.fill('停止後の下書き')
  await expect(button(page, '送信')).toBeEnabled()
  await shot(page, '09-child-interrupted-stopped')
})
