import { test, expect, visit, shot, nav, action, button, menu } from './helpers'

test('01a 一覧・ワークスペース切替・空一覧・会話から戻る', async ({ page }) => {
  await visit(page)
  await expect(page.locator('h1')).toHaveText('dsh-webui-m3e')
  await expect(page.locator('.home-session-button')).toContainText(['README の見直し', '承認シートの実装'])
  await shot(page, '01-home')
  await page.locator('m3e-icon-button[aria-label="ワークスペースを切り替え"]').click()
  await shot(page, '01-workspaces')
  await page.locator('[data-workspace-id="ws-harness"]').click()
  await expect(page.locator('h1')).toHaveText('deepseek-harness')
  await page.getByRole('button', { name: '接続のテストを整理', exact: true }).click()
  await expect(page.locator('h1')).toHaveText('接続のテストを整理')
  await button(page, '戻る').click()
  await expect(page.locator('h1')).toHaveText('deepseek-harness')
  await page.locator('m3e-icon-button[aria-label="ワークスペースを切り替え"]').click()
  await page.locator('[data-workspace-id="ws-notes"]').click()
  await expect(page.getByText('まだセッションがありません')).toBeVisible()
  await shot(page, '01-empty')
})

test('01b フォルダ選択・新規フォルダ・ワークスペース追加', async ({ page }) => {
  await visit(page)
  await page.locator('m3e-icon-button[aria-label="ワークスペースを切り替え"]').click()
  await page.locator('[data-add-workspace]').click()
  await expect(page.locator('h1')).toHaveText('フォルダを選ぶ')
  await shot(page, '01-directory')
  await button(page, '新しいフォルダ').click()
  await page.getByLabel('フォルダ名', { exact: true }).fill('統合確認')
  await button(page, 'OK').click()
  await page.getByRole('button', { name: '統合確認', exact: true }).click()
  await button(page, 'ここを追加').click()
  await expect(page.locator('h1')).toHaveText('統合確認')
  await expect(page.getByText('まだセッションがありません')).toBeVisible()
  await shot(page, '01-workspace-added')
})

test('01c 一覧メニュー・並べ替え・複数アーカイブ・子の会話', async ({ page }) => {
  await visit(page)
  await page.locator('m3e-icon-button[aria-label="一覧のメニュー"]').click()
  await shot(page, '01-home-menu')
  await page.locator('m3e-menu-item').filter({ hasText: '並べ替え' }).click()
  const first = page.locator('[data-session-id]').first()
  const id = await first.getAttribute('data-session-id')
  await first.locator('.home-drag-handle').press('ArrowDown')
  await expect(page.locator('[data-session-id]').nth(1)).toHaveAttribute('data-session-id', id!)
  await button(page, '完了').click()
  await page.locator('m3e-icon-button[aria-label="一覧のメニュー"]').click()
  await page.locator('m3e-menu-item').filter({ hasText: 'サブエージェントも表示' }).click()
  await expect(page.getByRole('button', { name: /一覧の表示をレビュー、子の会話/ })).toBeVisible()
  await page.getByRole('button', { name: /一覧の表示をレビュー、子の会話/ }).click()
  await expect(page.getByText('サブエージェントの会話は読むだけです')).toBeVisible()
  await button(page, '戻る').click()
  await page.locator('m3e-icon-button[aria-label="一覧のメニュー"]').click()
  await page.locator('m3e-menu-item').filter({ hasText: '選んでアーカイブ' }).click()
  await page.getByRole('button', { name: 'README の見直し', exact: true }).click()
  await page.getByRole('button', { name: '一覧のメニューを検討', exact: true }).click()
  await shot(page, '01-select-archive')
  await button(page, '2 件をアーカイブ').click()
  await expect(page.locator('.home-session-button').filter({ hasText: 'README の見直し' })).toHaveCount(0)
  await expect(page.locator('.home-session-button').filter({ hasText: '一覧のメニューを検討' })).toHaveCount(0)
})

test('02a チャット・考えた内容・ツール詳細・メッセージ操作', async ({ page }) => {
  await visit(page, '/s/readme-review')
  await expect(page.locator('.chat-assistant')).not.toHaveCount(0)
  await shot(page, '02-chat')
  const reasoning = page.locator('.chat-reasoning')
  await reasoning.locator('summary').click()
  await expect(reasoning).toHaveAttribute('open', '')
  await shot(page, '02-reasoning')
  await page.locator('.chat-tool').filter({ hasText: 'read_file' }).click()
  await expect(page.getByRole('heading', { name: 'ツール呼び出しの詳細' })).toBeVisible()
  await expect(page.locator('.chat-detail')).toContainText('README.md')
  await shot(page, '02-tool-detail')
  await button(page, '閉じる').click()
  await page.locator('.chat-tool').filter({ hasText: 'bash' }).click()
  await expect(page.getByText('ツールの実行に失敗しました。')).toBeVisible()
  await shot(page, '02-tool-error')
  await button(page, '閉じる').click()
  const message = page.locator('.chat-assistant .chat-message-action p').first()
  const bounds = await message.boundingBox()
  expect(bounds).not.toBeNull()
  await page.mouse.move(bounds!.x + bounds!.width / 2, bounds!.y + bounds!.height / 2)
  await page.mouse.down()
  await expect(button(page, 'ここから分岐')).toBeVisible()
  await shot(page, '02-message-actions-held')
  await page.mouse.up()
  await shot(page, '02-message-actions-released')
  await expect(button(page, 'ここから分岐')).toBeVisible()
  await button(page, 'ここから分岐').click()
  await expect(page).not.toHaveURL(/#\/s\/readme-review$/)
  await expect(page.locator('.chat-user')).not.toHaveCount(0)
})

test('02b チャットとトレースの往復で各スクロール位置・検索条件を保持', async ({ page }) => {
  await visit(page, '/s/chat-long')
  const chat = page.locator('.chat-scroll')
  await expect.poll(() => chat.evaluate(node => node.scrollHeight - node.clientHeight)).toBeGreaterThan(500)
  await expect.poll(() => chat.evaluate(node => node.scrollHeight - node.clientHeight - node.scrollTop)).toBeLessThan(3)
  const chatBottom = await chat.evaluate(node => node.scrollTop)
  await chat.hover()
  await page.mouse.wheel(0, -400)
  await expect.poll(() => chat.evaluate(node => node.scrollTop)).toBeLessThan(chatBottom - 200)
  const chatPosition = await chat.evaluate(node => node.scrollTop)
  await shot(page, '02-chat-scrolled')
  await page.getByRole('tab', { name: 'トレース', exact: true }).click()
  const trace = page.locator('.trace-scroll')
  await expect.poll(() => trace.evaluate(node => node.scrollHeight - node.clientHeight)).toBeGreaterThan(500)
  await expect(page.getByLabel('メッセージ入力欄')).toHaveCount(0)
  const traceStart = await trace.evaluate(node => node.scrollTop)
  await trace.hover()
  await page.mouse.wheel(0, -400)
  await expect.poll(() => trace.evaluate(node => node.scrollTop)).toBeLessThan(traceStart - 200)
  const tracePosition = await trace.evaluate(node => node.scrollTop)
  await shot(page, '04-trace-scrolled')
  await page.getByRole('tab', { name: 'チャット', exact: true }).click()
  await expect.poll(() => chat.evaluate(node => node.scrollTop)).toBeCloseTo(chatPosition, 0)
  await page.getByRole('tab', { name: 'トレース', exact: true }).click()
  await expect.poll(() => trace.evaluate(node => node.scrollTop)).toBeCloseTo(tracePosition, 0)
  await page.getByLabel('記録を検索').fill('確認')
  await page.getByRole('tab', { name: 'チャット', exact: true }).click()
  await page.getByRole('tab', { name: 'トレース', exact: true }).click()
  await expect(page.getByLabel('記録を検索')).toHaveValue('確認')
})

test('03a 新しいセッションは送信時に作成・Enter改行・下書き', async ({ page }) => {
  await visit(page)
  const count = await page.locator('.home-session-button').count()
  await button(page, '新しいセッション').click()
  await expect(page.getByText('何をしますか')).toBeVisible()
  await shot(page, '03-new')
  await page.getByLabel('メッセージ入力欄').fill('統合の確認')
  await page.getByLabel('メッセージ入力欄').press('Enter')
  await expect(page.getByLabel('メッセージ入力欄')).toHaveValue('統合の確認\n')
  await expect(page).toHaveURL(/#\/new\?ws=/)
  await button(page, '戻る').click()
  await expect(page.locator('.home-session-button')).toHaveCount(count)
  await button(page, '新しいセッション').click()
  await expect(page.getByLabel('メッセージ入力欄')).toHaveValue('統合の確認\n')
  await button(page, '送信').click()
  await expect(page).toHaveURL(/#\/s\//)
  await expect(page.locator('.chat-user')).toContainText(['統合の確認'])
  await shot(page, '03-created')
  await button(page, '戻る').click()
  await expect(page.locator('.home-session-button')).toHaveCount(count + 1)
})

test('03b 入力補助からモデルを選ぶ', async ({ page }) => {
  await visit(page, '/s/readme-review')
  await button(page, '入力の補助を開く').click()
  await shot(page, '03-plus')
  const model = page.locator('m3e-bottom-sheet[aria-label="入力の補助"] m3e-select[aria-label="モデル"]')
  await model.click()
  await shot(page, '03-model')
  await page.locator('m3e-option').filter({ hasText: 'ローカル / ローカル（ollama）' }).last().click()
  await expect(model).toHaveJSProperty('value', '6:ollamalocal')
})

test('03g 既存会話のコマンド・ファイル候補と画像の追加削除', async ({ page }) => {
  await visit(page, '/s/readme-review')
  const input = page.getByLabel('メッセージ入力欄')
  await input.fill('/')
  await expect(page.getByLabel('コマンドの候補')).toBeVisible()
  await shot(page, '03-command-suggestions')
  await input.fill('@docs')
  await page.getByRole('button', { name: 'docs/handoff.md', exact: true }).click()
  await expect(input).toHaveValue('@docs/handoff.md ')
  await shot(page, '03-file-reference')
  await page.locator('input[type="file"]').setInputFiles({ name: '確認.png', mimeType: 'image/png', buffer: Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+a5AAAAABJRU5ErkJggg==', 'base64') })
  await expect(page.locator('.composer-images img')).toBeVisible()
  await shot(page, '03-image')
  await button(page, '確認.png を外す').click()
  await expect(page.locator('.composer-images img')).toHaveCount(0)
})

test('03h 新規会話では初回送信前のコマンド・ファイル候補を案内に留める', async ({ page }) => {
  await visit(page, '/new?ws=ws-m3e')
  const input = page.getByLabel('メッセージ入力欄')
  await input.fill('/')
  await expect(page.getByText('ファイルとコマンドの候補は、最初の送信で会話を作ったあとに使えます。')).toBeVisible()
  await expect(page.getByLabel('コマンドの候補')).toHaveCount(0)
  await shot(page, '03-new-command-hint')
  await input.fill('@docs')
  await expect(page.getByLabel('ファイルの候補')).toHaveCount(0)
  await shot(page, '03-new-file-hint')
})

test('03c 実行中の順番待ち・複数行編集・割り込み・停止', async ({ page }) => {
  await visit(page, '/s/approval-sheet')
  await page.getByLabel('メッセージ入力欄').fill('順番待ちの確認')
  await button(page, '順番待ち').click()
  await button(page, '順番待ち 1 件').click()
  await shot(page, '03-queue')
  await button(page, '編集').click()
  await page.getByLabel('メッセージ', { exact: true }).fill('修正したメッセージ\n  二行目')
  await button(page, 'OK').click()
  await button(page, '順番待ち 1 件').click()
  await expect(page.locator('.composer-queue-preview')).toHaveText('修正したメッセージ\n  二行目')
  await button(page, '今すぐ割り込ませる').click()
  await page.getByLabel('メッセージ入力欄').fill('新しい割り込み')
  await button(page, '送り方を選ぶ').click()
  await shot(page, '03-delivery')
  await button(page, '割り込み').click()
  await button(page, '実行を停止').click()
  await expect(button(page, '送信')).toBeVisible()
  await expect(page).toHaveURL(/#\/s\/approval-sheet$/)
})

test('03d 新規会話の権限・計画モード・モデルの深さを選ぶ', async ({ page }) => {
  await visit(page, '/new?ws=ws-m3e')
  // Shared foundation sessions intentionally expose only one permission option.
  // New-session defaults come from 08 and contain both selectable presets.
  await button(page, 'ワークスペース書込').click()
  await shot(page, '03-permission')
  await page.getByRole('button', { name: /^フル アクセス/ }).click()
  await expect(button(page, 'フル アクセス')).toBeVisible()
  await button(page, '入力の補助を開く').click()
  await page.getByRole('switch', { name: '計画モード' }).click()
  await expect(page.getByRole('switch', { name: '計画モード' })).toBeChecked()
  const effort = page.locator('m3e-bottom-sheet[aria-label="入力の補助"] m3e-select[aria-label="考える深さ"]')
  await effort.click()
  await page.locator('m3e-option').filter({ hasText: 'オフ（考えない）' }).last().click()
  await expect(effort).toHaveJSProperty('value', 'off')
  await page.keyboard.press('Escape')
  await expect(page.locator('m3e-bottom-sheet[aria-label="入力の補助"]')).toHaveCount(0)
  await page.getByLabel('メッセージ入力欄').fill('設定を選んで開始')
  await button(page, '送信').click()
  await expect(page).toHaveURL(/#\/s\//)
  await expect(button(page, 'フル アクセス')).toBeVisible()
  await button(page, '入力の補助を開く').click()
  await expect(page.getByRole('switch', { name: '計画モード' })).toBeChecked()
  await shot(page, '03-plan-mode')
  await expect(page.locator('m3e-bottom-sheet[aria-label="入力の補助"] m3e-select[aria-label="考える深さ"]')).toHaveJSProperty('value', 'off')
  await shot(page, '03-reasoning-effort')
})

test('04a トレースの記録詳細・絞り込み・空結果', async ({ page }) => {
  await visit(page, '/s/approval-sheet/trace')
  await expect(page.locator('.trace-turn')).not.toHaveCount(0)
  await shot(page, '04-trace')
  await page.locator('[data-trace-row]').filter({ hasText: 'bash' }).first().click()
  await expect(page.getByRole('dialog', { name: '記録の詳細' })).toBeVisible()
  await shot(page, '04-record')
  await button(page, '閉じる').click()
  await page.getByLabel('記録を検索').fill('bash')
  await expect(page.locator('[data-trace-row]')).toHaveCount(2)
  await shot(page, '04-filter')
  await page.getByLabel('記録を検索').fill('存在しない検索語')
  await expect(page.getByText('一致する記録がありません。')).toBeVisible()
})

for (const tab of ['chat', 'trace']) test(`05a-${tab} 承認は払っても閉じず回答で入力が戻る`, async ({ page }) => {
  await visit(page, `/s/approval-sheet${tab === 'trace' ? '/trace' : ''}`, 'approval')
  const dialog = page.getByRole('dialog', { name: 'ツールの承認', exact: true })
  await expect(dialog).toBeVisible()
  await expect(page.getByLabel('メッセージ入力欄')).toHaveCount(0)
  await page.keyboard.press('Escape')
  await expect(dialog).toBeVisible()
  const bounds = await dialog.boundingBox()
  expect(bounds).not.toBeNull()
  await page.mouse.move(bounds!.x + bounds!.width / 2, bounds!.y + 8)
  await page.mouse.down()
  await page.mouse.move(bounds!.x + bounds!.width / 2, 830, { steps: 10 })
  await page.mouse.up()
  await expect(dialog).toBeVisible()
  await shot(page, `05-approval-${tab}`)
  await button(page, '許可（1 回）').click()
  await expect(dialog).toHaveCount(0)
  if (tab === 'trace') await page.getByRole('tab', { name: 'チャット', exact: true }).click()
  await expect(page.getByLabel('メッセージ入力欄')).toBeVisible()
})

test('05b 承認のトレース退避からチャットへ戻っても入力を隠す', async ({ page }) => {
  await visit(page, '/s/approval-sheet', 'approval')
  await button(page, 'トレースで見る').click()
  await expect(page).toHaveURL(/\/trace$/)
  await page.getByRole('tab', { name: 'チャット', exact: true }).click()
  await expect(page.getByLabel('メッセージ入力欄')).toHaveCount(0)
  await shot(page, '05-approval-deferred')
  await page.locator('.interaction-pending-chips m3e-assist-chip').click()
  await button(page, '拒否').click()
  await expect(page.getByLabel('メッセージ入力欄')).toBeVisible()
})

test('05c approval-cancel は自動で閉じ入力を戻す', async ({ page }) => {
  await visit(page, '/s/approval-sheet', 'approval-cancel')
  await expect(page.getByRole('dialog', { name: 'ツールの承認' })).toBeVisible()
  await shot(page, '05-approval-cancel-pending')
  await expect(page.getByRole('dialog', { name: 'ツールの承認' })).toHaveCount(0, { timeout: 10_000 })
  await expect(page.getByLabel('メッセージ入力欄')).toBeVisible()
  await shot(page, '05-approval-cancelled')
})

test('05d question の選択・複数選択・あとでと下書き保持', async ({ page }) => {
  await visit(page, '/s/05-db-choice', 'question')
  await expect(button(page, '次へ')).toBeDisabled()
  await page.locator('.interaction-option').filter({ hasText: 'SQLite' }).click()
  await shot(page, '05-question-single')
  await button(page, '次へ').click()
  await page.locator('.interaction-option').filter({ hasText: 'データの移行' }).click()
  await page.locator('.interaction-option').filter({ hasText: 'バックアップ' }).click()
  await page.getByLabel('その他（自由に書く）').fill('復元の時間も確認')
  await shot(page, '05-question-multiple')
  await button(page, 'あとで').click()
  await expect(page.getByLabel('メッセージ入力欄')).toBeVisible()
  await page.locator('.interaction-pending-chips m3e-assist-chip').click()
  await expect(page.getByLabel('その他（自由に書く）')).toHaveValue('復元の時間も確認')
  await button(page, '回答する').click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
})

for (const approve of [true, false]) test(`05e-${approve ? 'approve' : 'revise'} plan の全文表示と回答`, async ({ page }) => {
  await visit(page, '/s/05-auth-redesign', 'plan')
  await expect(page.getByRole('heading', { name: 'プランの確認' })).toBeVisible()
  await shot(page, approve ? '05-plan' : '05-plan-before-revision')
  if (approve) await button(page, 'このプランで進める').click()
  else {
    await button(page, '直してほしい').click()
    await page.getByLabel('直してほしいこと', { exact: true }).fill('まずテストから実施してください')
    await shot(page, '05-plan-revision')
    await button(page, '修正をお願いする').click()
  }
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(page.getByLabel('メッセージ入力欄')).toBeVisible()
})

test('06a 対応待ちから会話を開かず質問・プラン・承認に回答', async ({ page }) => {
  await visit(page, '/inbox', 'inbox')
  await expect(page.locator('#inbox-pending-heading')).toHaveText('返事が必要')
  await expect(action(page, '一覧の表示方法')).toBeVisible()
  await shot(page, '06-inbox')
  const initial = await page.locator('.count-badge').textContent()
  await action(page, '一覧の表示方法').click()
  await page.locator('.interaction-option').filter({ hasText: 'すべて表示' }).click()
  await button(page, '回答する').click()
  await expect(page).toHaveURL(/#\/inbox$/)
  await expect(page.locator('.count-badge')).toHaveText(String(Number(initial) - 1))
  await action(page, 'スマートフォン画面の改善').click()
  await shot(page, '06-inbox-plan')
  await button(page, '承認して開始').click()
  await expect(page).toHaveURL(/#\/inbox$/)
  await action(page, '対応待ちのテスト').click()
  await shot(page, '06-inbox-approval')
  await button(page, '拒否').click()
  await expect(page).toHaveURL(/#\/inbox$/)
  await action(page, '操作手順の見直し').click()
  await expect(page.locator('h1')).toHaveText('操作手順の見直し')
  await button(page, '戻る').click()
  await expect(action(page, '操作手順の見直し')).toHaveCount(0)
})

test('07a 検索結果・強調・会話から戻り入力と結果を保持', async ({ page }) => {
  await visit(page)
  await nav(page, '検索').click()
  await shot(page, '07-recent')
  await page.getByLabel('セッションを検索').fill('README')
  await expect(action(page, 'README の見直し')).toBeVisible()
  await expect(page.locator('.search-snippet strong').first()).toHaveText(/README/i)
  await shot(page, '07-results')
  await action(page, 'README の見直し').click()
  await page.getByRole('tab', { name: 'トレース', exact: true }).click()
  await button(page, '戻る').click()
  await expect(page).toHaveURL(/#\/search$/)
  await expect(page.getByLabel('セッションを検索')).toHaveValue('README')
  await expect(action(page, 'README の見直し')).toBeVisible()
  await page.getByLabel('セッションを検索').fill('存在しない検索語')
  await expect(page.getByText('見つかりませんでした', { exact: true })).toBeVisible()
  await shot(page, '07-empty')
})

test('07b search-more の上限と追加結果の案内', async ({ page }) => {
  await visit(page, '/search', 'search-more')
  await page.getByLabel('セッションを検索').fill('検索の追加結果')
  await expect(page.getByText('さらに結果があります。語を増やして絞り込んでください')).toBeVisible()
  await shot(page, '07-more')
  await expect(page.locator('.search-results m3e-list-action')).toHaveCount(20)
})

test('07c search-error の失敗表示と再試行', async ({ page }) => {
  await visit(page, '/search', 'search-error')
  await page.getByLabel('セッションを検索').fill('承認')
  await expect(page.getByText('検索できませんでした', { exact: true })).toBeVisible()
  await shot(page, '07-error')
  await button(page, 'もう一度検索').click()
  await expect(page.getByText('検索できませんでした', { exact: true })).toBeVisible()
})

test('08a 設定の各ページ・保存・既定値・外観・標準画面の確認', async ({ page }) => {
  await visit(page, '/settings')
  await shot(page, '08-settings')
  for (const [label, id] of [['モデル', 'models'], ['権限', 'permission'], ['エージェント', 'agent'], ['Web 検索とシェル', 'tools'], ['そのほか', 'other']]) {
    await action(page, label!).first().click()
    await expect(page.locator('h1')).toHaveText(label)
    await shot(page, `08-${id}`)
    await button(page, '戻る').click()
  }
  await action(page, '外観').click()
  await page.getByRole('radio', { name: 'ダーク' }).click()
  await expect(page.locator('html')).toHaveCSS('color-scheme', 'dark')
  await shot(page, '08-appearance-dark')
  await page.keyboard.press('Escape')
  await page.reload()
  await expect(page.locator('html')).toHaveCSS('color-scheme', 'dark')
  await action(page, '今の画面に戻す').click()
  await shot(page, '08-classic-confirm')
  await button(page, 'キャンセル').click()
  await expect(page).toHaveURL(/#\/settings$/)
})

test('08b APIキーの登録状況・架空値の保存・空の再表示・削除', async ({ page }) => {
  await visit(page, '/settings/providers')
  await expect(action(page, 'ディープシーク')).toContainText('登録済み')
  await shot(page, '08-providers')
  await action(page, 'クラウド提供元').click()
  const key = page.getByLabel('API キー', { exact: true })
  await expect(key).toHaveValue('')
  await key.fill('mock-e2e-not-a-real-key')
  await expect(key).toHaveAttribute('type', 'password')
  await button(page, '入力したキーを表示する').click()
  await expect(key).toHaveAttribute('type', 'text')
  await button(page, '入力したキーを隠す').click()
  await shot(page, '08-api-key')
  await button(page, '保存').click()
  await expect(action(page, 'クラウド提供元')).toContainText('登録済み')
  await action(page, 'クラウド提供元').click()
  await expect(key).toHaveValue('')
  await button(page, '登録を消す').click()
  await shot(page, '08-api-key-remove')
  await button(page, '登録を消す').click()
  await expect(action(page, 'クラウド提供元')).toContainText('未登録')
})

test('09a 会話メニューから統計・ファイル・ジョブ・子の会話', async ({ page }) => {
  await visit(page, '/s/approval-sheet')
  await menu(page, '統計')
  await expect(page.getByRole('heading', { name: '統計', exact: true })).toBeVisible()
  await shot(page, '09-stats')
  await button(page, '閉じる').click()
  await menu(page, 'ファイル')
  await shot(page, '09-files')
  await action(page, 'README.md').click()
  await expect(page.getByText('スマートフォン向けの画面', { exact: true })).toBeVisible()
  await shot(page, '09-file-markdown')
  await button(page, '戻る').click()
  await action(page, 'preview.png').click()
  await expect(page.locator('.session-file-image')).toBeVisible()
  await shot(page, '09-file-image')
  await button(page, '戻る').click()
  await button(page, '戻る').click()
  await menu(page, 'ジョブ')
  await expect(page.getByText('型を確認しています', { exact: true })).toBeVisible()
  await shot(page, '09-jobs')
  await button(page, '戻る').click()
  await menu(page, 'サブエージェント')
  await shot(page, '09-subagents')
  await action(page, '承認シートの見直し').click()
  await expect(page.getByLabel('メッセージ入力欄', { exact: true })).toBeVisible()
  await expect(page.getByRole('heading', { name: '承認シートの見直し', exact: true })).toBeVisible()
  await shot(page, '09-child-conversation')
})

test('09b ゴールの一時停止・再開・完了・削除', async ({ page }) => {
  await visit(page, '/s/approval-sheet')
  await menu(page, 'ゴール')
  await expect(page.getByText('承認シートを作り、テストで操作を確かめる', { exact: true })).toBeVisible()
  await shot(page, '09-goal')
  await button(page, '一時停止').click()
  await expect(button(page, '再開')).toBeVisible()
  await button(page, '再開').click()
  await expect(button(page, '一時停止')).toBeVisible()
  await button(page, '完了にする').click()
  await expect(button(page, '完了にする')).toHaveCount(0)
  await button(page, 'ゴールを消す').click()
  await shot(page, '09-goal-clear')
  await page.locator('m3e-dialog m3e-button').filter({ hasText: 'ゴールを消す' }).click()
  await expect(page.getByText('ゴールはありません。')).toBeVisible()
})

test('09c 題名変更とアーカイブ', async ({ page }) => {
  await visit(page, '/s/readme-review')
  await menu(page, '題名を変える')
  await page.getByLabel('題名', { exact: true }).fill('統合試験で変更した会話')
  await shot(page, '09-rename')
  await button(page, 'OK').click()
  await expect(page.locator('h1')).toHaveText('統合試験で変更した会話')
  await menu(page, 'アーカイブ')
  await expect(page).toHaveURL(/#\/$/)
  await expect(page.locator('.home-session-button').filter({ hasText: '統合試験で変更した会話' })).toHaveCount(0)
})

test('00a 切断バナー・作成禁止・再接続', async ({ page }) => {
  await visit(page, '/', 'disconnected')
  await expect(page.getByText('DSH との接続が切れました')).toBeVisible()
  await expect(button(page, '新しいセッション')).toBeDisabled()
  await shot(page, '00-disconnected')
  await button(page, '再接続').click()
  await expect(page.getByText('DSH との接続が切れました')).toHaveCount(0)
  await expect(button(page, '新しいセッション')).toBeEnabled()
})

test('00b 再接続中の進捗表示', async ({ page }) => {
  await visit(page, '/', 'reconnecting')
  await expect(page.getByRole('progressbar', { name: '再接続中' })).toBeVisible()
  await shot(page, '00-reconnecting')
})

test('00c 詳細への直接アクセスから戻る・左端スワイプ', async ({ page }) => {
  await visit(page, '/s/readme-review')
  await button(page, '戻る').click()
  await expect(page).toHaveURL(/#\/$/)
  await page.getByRole('button', { name: 'README の見直し', exact: true }).click()
  await expect(page.locator('.edge-swipe-zone')).toBeVisible()
  await page.mouse.move(2, 200)
  await page.mouse.down()
  // Ten traced CDP moves can exceed the gesture's 1200ms window on a busy host.
  // This test exercises one quick swipe, with the same start and end points.
  await page.mouse.move(180, 210)
  await page.mouse.up()
  await expect(page).toHaveURL(/#\/$/)
})

test('10a 開発mockのPWAメタデータとSW未登録', async ({ page }) => {
  await visit(page)
  await expect(page.locator('link[rel="manifest"]')).toHaveAttribute('href', /\/m3e\/manifest\.webmanifest/)
  const response = await page.request.get('/m3e/manifest.webmanifest')
  expect(response.ok()).toBeTruthy()
  const manifest = await response.json()
  expect(manifest.scope).toBe('/m3e/')
  expect(manifest.start_url).toBe('/m3e/')
  expect(manifest.display).toBe('standalone')
  expect(await page.evaluate(async () => (await navigator.serviceWorker.getRegistrations()).length)).toBe(0)
  await expect(page.locator('meta[name="apple-mobile-web-app-capable"]')).toHaveAttribute('content', 'yes')
})
