import { test, expect, visit, shot, action, button } from './helpers'

test('01i 一覧の長押し操作シートはポインターを離しても残る', async ({ page }) => {
  await visit(page)
  const row = page.getByRole('button', { name: 'README の見直し', exact: true })
  const bounds = await row.boundingBox()
  expect(bounds).not.toBeNull()
  await page.mouse.move(bounds!.x + bounds!.width / 2, bounds!.y + bounds!.height / 2)
  await page.mouse.down()
  await expect(page.getByRole('dialog')).toBeVisible()
  await shot(page, '01-session-actions-held')
  await page.mouse.up()
  await shot(page, '01-session-actions-released')
  await expect(page.getByRole('dialog')).toBeVisible()
})

test('01j ワークスペースの名前を変える', async ({ page }) => {
  await visit(page)
  await page.locator('m3e-icon-button[aria-label="一覧のメニュー"]').click()
  await page.locator('m3e-menu-item').filter({ hasText: '名前を変える' }).click()
  await page.getByLabel('名前', { exact: true }).fill('統合のワークスペース')
  await button(page, 'OK').click()
  await expect(page.locator('h1')).toHaveText('統合のワークスペース')
  await shot(page, '01-workspace-renamed')
})

test('03e 順番待ちを取り消す', async ({ page }) => {
  await visit(page, '/s/approval-sheet')
  await page.getByLabel('メッセージ入力欄').fill('取り消す待ちメッセージ')
  await button(page, '順番待ち').click()
  await button(page, '順番待ち 1 件').click()
  await button(page, '取り消す').click()
  await expect(button(page, '順番待ち 1 件')).toHaveCount(0)
  await expect(button(page, '実行を停止')).toBeVisible()
  await shot(page, '03-queue-removed')
})

test('03f 切断中は下書きを保持して送信しない', async ({ page }) => {
  await visit(page, '/s/readme-review', 'disconnected')
  await page.getByLabel('メッセージ入力欄').fill('接続が戻るまで下書き')
  await expect(button(page, '送信')).toBeDisabled()
  await shot(page, '03-disconnected-draft')
  await button(page, '再接続').click()
  await expect(button(page, '送信')).toBeEnabled()
  await expect(page.getByLabel('メッセージ入力欄')).toHaveValue('接続が戻るまで下書き')
})

test('06b 空の対応待ちを表示する', async ({ page }) => {
  await visit(page, '/inbox', 'empty')
  await expect(page.getByText('対応待ちはありません', { exact: true })).toBeVisible()
  await expect(page.locator('.count-badge')).toHaveCount(0)
  await shot(page, '06-empty')
})

test('08h 設定の真偽・数値・選択肢・入れ子を保存する', async ({ page }) => {
  await visit(page, '/settings/permission')
  const enabled = page.getByRole('switch', { name: '有効にする', exact: true })
  const initial = await enabled.isChecked()
  await enabled.click()
  await expect(enabled).toBeChecked({ checked: !initial })
  const number = page.getByLabel('待機時間', { exact: true })
  await number.fill('24')
  await number.press('Tab')
  await page.locator('m3e-select[aria-label="動作モード"]').click()
  await page.getByRole('option').last().click()
  const nested = page.getByLabel('間隔', { exact: true })
  await nested.fill('7')
  await nested.press('Tab')
  await expect(page.locator('.settings-saving').filter({ hasText: '保存しました' })).not.toHaveCount(0)
  await button(page, '戻る').click()
  await page.locator('m3e-nav-item').filter({ hasText: '設定' }).click()
  await action(page, '権限').click()
  await expect(enabled).toBeChecked({ checked: !initial })
  await expect(number).toHaveValue('24')
  await expect(nested).toHaveValue('7')
  await shot(page, '08-fields-saved')
})
