import { test, expect, visit, action, button } from './helpers'

test('下位に high があっても非対応モデル・モデル既定を保存し、リセットでは継承する', async ({ page }) => {
  await visit(page, '/settings', 'settings-inherited-reasoning')
  await action(page, 'モデル').first().click()
  const model = page.locator('m3e-select[aria-label="モデル"]')
  const effort = page.locator('m3e-select[aria-label="推論の強さ"]')
  await expect(effort).toHaveJSProperty('value', 'high')
  await model.click()
  await page.locator('m3e-option').filter({ hasText: 'ローカル / ローカル（ollama）' }).last().click()
  await expect(model).toHaveJSProperty('value', '6:ollamalocal')
  await expect(effort).toBeHidden()
  await expect(page.getByText('保存しました', { exact: true })).toBeVisible()
  await button(page, '戻る').click()
  await action(page, 'モデル').first().click()
  await expect(model).toHaveJSProperty('value', '6:ollamalocal')
  await model.click()
  await page.locator('m3e-option').filter({ hasText: 'DeepSeek / DeepSeek V4' }).last().click()
  await expect(effort).toHaveJSProperty('value', 'high')
  await effort.click()
  await page.locator('m3e-option').filter({ hasText: '既定（モデルに任せる）' }).last().click()
  await expect(effort.locator('[slot="value"]')).toHaveText('既定（モデルに任せる）')
  await expect(page.getByText('保存しました', { exact: true })).toBeVisible()
  await button(page, '戻る').click()
  await action(page, 'モデル').first().click()
  await expect(effort.locator('[slot="value"]')).toHaveText('既定（モデルに任せる）')
  await button(page, '既定のモデルを既定値に戻す').click()
  await expect(effort).toHaveJSProperty('value', 'high')
})
