import { test, expect, visit, action, button, nav } from './helpers'

test('08 モデルと推論の強さを選んで保存し、詳細を開き直しても残る', async ({ page }) => {
  await visit(page, '/settings')
  await expect(action(page, 'モデル').first()).toContainText('deepseek-v4')
  await action(page, 'モデル').first().click()
  await expect(page.locator('h1')).toHaveText('モデル')
  const model = page.locator('m3e-select[aria-label="モデル"]')
  const effort = page.locator('m3e-select[aria-label="推論の強さ"]')
  await expect(model).toHaveJSProperty('value', '8:deepseekdeepseek-v4')
  await expect(effort).toHaveJSProperty('value', 'high')

  await model.click()
  await page.locator('m3e-option').filter({ hasText: 'ローカル / ローカル（ollama）' }).last().click()
  await expect(model).toHaveJSProperty('value', '6:ollamalocal')
  await expect(effort).toBeHidden()
  await page.setViewportSize({ width: 375, height: 844 })
  await expect(effort.locator('..').locator('..')).toHaveCSS('display', 'none')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await expect(page.getByText('保存しました', { exact: true })).toBeVisible()
  await button(page, '戻る').click()
  await expect(action(page, 'モデル').first()).toContainText('local')
  await action(page, 'モデル').first().click()
  await expect(model).toHaveJSProperty('value', '6:ollamalocal')
  await expect(effort).toBeHidden()

  await model.click()
  await page.locator('m3e-option').filter({ hasText: 'DeepSeek / DeepSeek V4' }).last().click()
  await expect(effort).toBeVisible()
  await expect(effort).toHaveJSProperty('value', 'high')
  await expect(effort).toHaveJSProperty('disabled', false)
  await expect(effort.locator('m3e-option')).toHaveCount(5)
  await expect.poll(() => effort.evaluate(element => (element as HTMLElement & { options: unknown[] }).options.length)).toBe(5)
  await effort.click()
  await expect(effort).toHaveAttribute('aria-expanded', 'true')
  await page.locator('m3e-option').filter({ hasText: '低' }).last().click()
  await expect(effort).toHaveJSProperty('value', 'low')
  await expect(page.getByText('保存しました', { exact: true })).toBeVisible()
  await effort.click()
  await page.locator('m3e-option').filter({ hasText: '既定（モデルに任せる）' }).last().click()
  await expect(effort).toHaveJSProperty('value', null)
  await expect(effort.locator('[slot="value"]')).toHaveText('既定（モデルに任せる）')
  await expect(page.getByText('保存しました', { exact: true })).toBeVisible()
  await button(page, '戻る').click()
  await action(page, 'モデル').first().click()
  await expect(model).toHaveJSProperty('value', '8:deepseekdeepseek-v4')
  await expect(effort).toHaveJSProperty('value', null)
  await button(page, '既定のモデルを既定値に戻す').click()
  await expect(effort.locator('[slot="value"]')).toHaveText('既定（モデルに任せる）')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('08 サブエージェントの許可モデルを追加・削除して開き直せる', async ({ page }) => {
  await visit(page, '/settings/models')
  const enabled = page.locator('m3e-switch[aria-label="サブエージェントのモデルを有効にする"]')
  const deepseek = page.locator('m3e-checkbox[aria-label="DeepSeek / DeepSeek V4"]')
  const local = page.locator('m3e-checkbox[aria-label="ローカル / ローカル（ollama）"]')
  await expect(enabled).toHaveJSProperty('disabled', true)
  await expect(enabled).toHaveJSProperty('checked', false)
  await expect(page.getByText('先に使ってよいモデルを 1 つ以上選んでください')).toBeVisible()
  await expect(deepseek).toHaveJSProperty('disabled', false)
  await deepseek.click()
  await expect(enabled).toHaveJSProperty('disabled', false)
  await deepseek.click()
  await expect(enabled).toHaveJSProperty('disabled', true)
  await deepseek.click()
  await enabled.click()
  await expect(enabled).toHaveJSProperty('checked', true)
  await expect(deepseek).toHaveJSProperty('disabled', true)
  await expect(page.getByText('有効の間は 1 つ以上必要です')).toBeVisible()
  await local.click()
  await expect(deepseek).toHaveJSProperty('disabled', false)
  await expect(deepseek).toHaveJSProperty('checked', true)
  await expect(local).toHaveJSProperty('checked', true)
  await deepseek.click()
  await expect(deepseek).toHaveJSProperty('checked', false)
  await expect(local).toHaveJSProperty('checked', true)
  await expect(page.getByText('保存しました', { exact: true })).toBeVisible()
  await button(page, '戻る').click()
  await nav(page, '設定').click()
  await action(page, 'モデル').first().click()
  await expect(enabled).toHaveJSProperty('checked', true)
  await expect(deepseek).toHaveJSProperty('checked', false)
  await expect(local).toHaveJSProperty('checked', true)
})

test('08 モデル設定の読み取り専用と保存拒否を示す', async ({ page }) => {
  await visit(page, '/settings/models', 'settings-readonly')
  await expect(page.getByText('この DSH では設定を変更できません', { exact: true })).toBeVisible()
  await expect(page.locator('m3e-select[aria-label="モデル"]')).toHaveJSProperty('disabled', true)
  await expect(page.locator('m3e-switch[aria-label="サブエージェントのモデルを有効にする"]')).toHaveJSProperty('disabled', true)
  await visit(page, '/settings/models', 'settings-rejected')
  const model = page.locator('m3e-select[aria-label="モデル"]')
  await model.click()
  await page.locator('m3e-option').filter({ hasText: 'ローカル / ローカル（ollama）' }).last().click()
  await expect(page.getByRole('alert')).toHaveText('この値は管理者の設定によって許可されていません。')
  await expect(model).toHaveJSProperty('value', '8:deepseekdeepseek-v4')
})
